name: Build Catalog

on:
  push:
    paths-ignore:
      - '*.md'
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -   # Copies the repository files to the Action Runner
        name: Checkout Repository
        uses: actions/checkout@v4.1.0

      -
        name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16.x

      - # Upload Async API files to storage
        name: Move Async API files to Catalog
        run: |
          cp account-service/asyncapi.yaml catalog/asyncapi/account-service.yaml
          cp payment-service/asyncapi.yaml catalog/asyncapi/payment-service.yaml

      - # Generate Catalog from Async API files
        name: Generate Catalog
        run: cd catalog && npm install

      - # Generate Catalog from Async API files
        name: Generate Catalog
        run: cd catalog && npm run generate

      - # Generate Catalog from Async API files
        name: Generate Catalog
        run: cd catalog && npm run build

      # Generate Catalog from Async API files
      # Build Image...
